name: build and test

on: push

jobs:
  lint:
    name: Lint application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1

      - name: Install poetry
        uses: Gr1N/setup-poetry@v7

      - run: |
          poetry install
          poetry run black --check --line-length 79 .
          poetry run flake8 .
          poetry run isort --check .

  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1

      - name: Install poetry
        uses: Gr1N/setup-poetry@v7

      - run: |
          poetry install
          poetry run pytest server/test
