name: build and test

on: push

jobs:
  lint:
    name: Lint application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1

      - name: Install poetry
        uses: Gr1N/setup-poetry@v7

      - run: |
          poetry install
          poetry run black --check --line-length 79 .
          poetry run flake8 .
          poetry run isort --check .

  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1

      - name: Install poetry
        uses: Gr1N/setup-poetry@v7

      - run: |
          poetry install
          poetry run pytest server/test

  build:
    needs: [lint, test]
    name: Build and publish docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: cphalen/exchange-server:${{ github.sha }}

